[package]
name = "wmms-model"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
wmms-core = { workspace = true }
wmms-aspects = { workspace = true }

roaring = { workspace = true }
