[package]
name = "wmms-aspects"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
wmms-core = {workspace = true}
thiserror = {workspace = true}
miette = {workspace = true}
